package com.lafiray.springboot.enums;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum CatgoryEnum {
    FREINAGE("FREINAGE"),
    FILTRATION_HUILE_VIDANGE("FILTRATION_HUILE_VIDANGE"),
    TRAINS_AV_AR_SUSPENSION("TRAINS_AV_AR_SUSPENSION"),
    EMBRAYAGES_BOITE_TRANSMISSION("EMBRAYAGES_BOITE_TRANSMISSION"),
    COMPARTIMENT_MOTEUR("COMPARTIMENT_MOTEUR"),
    EQUIPEMENTS_EXTERIEURS("EQUIPEMENTS_EXTERIEURS"),
    ECHAPPEMENT("ECHAPPEMENT"),
    ELECTRICITE("ELECTRICITE");


    private String categoryLabel;

}
